### PR TITLE
Handshake fix

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
Fix for webseeds

### CODE REVIEW

**Comment by rom1504** [comment]
what is `this` in a listener ? https://nodejs.org/api/events.html#events_emitter_on_event_listener doesn't say anything about it

**Comment by DiegoRBaquero** [comment]
this would be the bittorrent-swarm itself

**Comment by DiegoRBaquero** [comment]
This is so wrong, but got it fixed.

**Comment by feross** [comment]
Good catch. I broke this when I published `bittorrent-protocol@2.0.0` two weeks ago. Thanks for the fix!

**Comment by feross** [comment]
Released as 6.0.1.

**Pull request merged**
