### PR TITLE
Multiple file support for webseed.

### PR DESCRIPTION
**Pull request by solderzzc**

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR! Can you add a test that proves this code is working?

Also, please use the `run-parallel-limit` package instead of `async`. `async` is huge and we can't use it in the browser.

**Comment by solderzzc** [comment]
@feross I'll use run-parallel-limit package instead of async. I did the test by adding url-list 'http://localhost:8080/' but I don't how to write test script with local http server, please advise.

**Comment by solderzzc** [comment]
@feross  Changed to run-parallel-limit, the test script also committed.

**Comment by gcoupelant** [comment]
+1

**Comment by gcoupelant** [comment]
Any news here ? :+1:

**Comment by feross** [comment]
Thanks for the PR. Web seeding multiple files is supported now!

**Pull request closed without merging**
